POST http://localhost:8080/org/index
Content-Type: application/json

{
	"org_name": "Paradise Island",
	"parent": 0
}

###

POST http://localhost:8080/org/add
Content-Type: application/json

{
  "org_name": "Paradise Island",
  "daughters": [
    {
      "org_name": "Banana Tree",
      "daughters": [
        {
          "org_name": "Yellow Banana"
        },
        {
          "org_name": "Brown Banana"
        },
        {
          "org_name": "Black Banana"
        }
      ]
    },
    {
      "org_name": "Big Banana Tree",
      "daughters": [
        {
          "org_name": "Yellow Banana"
        },
        {
          "org_name": "Brown Banana"
        },
        {
          "org_name": "Black Banana",
          "daughters": {
            "org_name": "Phoneutria Spider"
          }
        }
      ]
    }
  ]
}